---
title: "Week 4"
output: html_document
---

  
  ```{r, echo=F}
library(MASS)
str(Boston)
dim(Boston)
head(Boston)
```

3.
```{r}
plot(Boston)
summary(Boston)
```

4.
```{r}
boston_scaled<- scale(Boston)
head(boston_scaled)
summary(boston_scaled)

boston_scaled<-as.data.frame(boston_scaled)

scaled_crim <- boston_scaled$crim
bins <- quantile(scaled_crim)

crime<- cut(scaled_crim, breaks= bins, include.lowest=T,labels
            =c("low", "med_low", "med_high", "high"))
boston_scaled <- dplyr::select(boston_scaled, -crim)
boston_scaled <- data.frame(boston_scaled, crime)

n <- nrow(boston_scaled)
ind <- sample(n,  size = n * 0.8)
train<-boston_scaled[ind,]
test<- boston_scaled[-ind,]


```


5.
```{r}
lda.fit<-lda(crime~., train)

#tulkinta

lda.arrows <- function(x, myscale = 1, arrow_heads = 0.1, color = "red", tex = 0.75, choices = c(1,2)){
  heads <- coef(x)
  arrows(x0 = 0, y0 = 0, 
         x1 = myscale * heads[,choices[1]], 
         y1 = myscale * heads[,choices[2]], col=color, length = arrow_heads)
  text(myscale * heads[,choices], labels = row.names(heads), 
       cex = tex, col=color, pos=3)
}

classes <- as.numeric(train$crime)

plot(lda.fit, dimen = 2, col=classes, pch=classes)
#mit???
lda.arrows(lda.fit, myscale = 1)

```
6.

```{r}
correct_classes <-test$crime


test<-dplyr::select(test, -crime)

lda.pred <- predict(lda.fit, newdata = test)
table(correct = correct_classes, predicted = lda.pred$class)

class(correct_classes)
class(lda.pred$class)


```
7.
```{r}

boston_data<-as.data.frame(scale(Boston))

dist_eu<-dist(boston_data)
dist_man <- dist(boston_data, method="manhattan")

km <-kmeans(boston_data, centers = 4)

set.seed(33)
k_max <- 10

twcss <- sapply(1:k_max, function(k){kmeans(Boston, k)$tot.withinss})

library(ggplot2)
qplot(x = 1:k_max, y = twcss, geom = "line")

km <-kmeans(boston_data, centers = 2)

pairs(boston_data, col = km$cluster)

library(GGally)
ggpairs(boston_data, col= km$cluster)

```

```{r}
set.seed(777)
library(MASS)
bst <- as.data.frame(scale(Boston))
km_5 <- kmeans(bst, centers = 5)
lda.fit2 <- lda(km_5$cluster ~ ., data = bst)
# target classes as numeric
class <- as.numeric(km_5$cluster)
# plot the lda results
plot(lda.fit2, dimen = 2, col = class , pch = class)
lda.arrows(lda.fit2, myscale = 1)
```

It seems rad is very influential.
```
